### ISSUE TITLE
如何学习hypervisor开发

### ISSUE THREAD

**Issue by wangzhankun** [KuangjuX/hypocaust#6]
你好，我现在也在学习开发vmm，但是只找到了一些虚拟化原理的书籍，请问您可以推荐一些如何实现VMM的教程和书籍吗？

**Comment by KuangjuX** [comment]
你好，VMM 基本上没有什么太多的关于开发的书籍，我也基本上是看 USCD 的 lecture 学的，关于 x86 的虚拟化可以看看 equation314 大佬的 RVM-tutorial 教程: https://github.com/equation314/RVM-Tutorial，也欢迎加我微信交流：KuangjuX










在 2023-02-07 21:23:26，"wangzhankun" ***@***.***> 写道：

你好，我现在也在学习开发vmm，但是只找到了一些虚拟化原理的书籍，请问您可以推荐一些如何实现VMM的教程和书籍吗？

**Comment by KuangjuX** [comment]
我也是看的 USCD 的 lecture 来写的，市面上基本上没有实现 VMM 的书籍，关于实现 x86 虚拟化可以看看 equation314 的 [RVM-Tutorial](https://github.com/equation314/RVM-Tutorial)
